[env]
TERM = "xterm-256color"

[font]
size = 7.0

[window]
opacity = 1.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
