shadow = true;
shadow-radius = 10;
shadow-offset-x = -7;
shadow-offset-y = -7;

fading = true;
fade-delta = 5

frame-opacity = 0.9;

corner-radius = 2;

backend = "glx";
vsync = false;
unredir-if-possible = false
detect-client-opacity = false;
use-damage = true;
detect-rounded-corners = false;
