# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -ogq @catppuccin_window_text " #W"
set -ogq @catppuccin_window_current_text " #W"
set -ogq @catppuccin_status_left_separator "█"
set -ogq @catppuccin_status_right_separator "█"

# Load catppuccin
run ~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_session} "
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Send status bar to the top
set-option -g status-position top

# Enable true color
set -g default-terminal "tmux-256color"

# Bind prefix + r to reload config file
unbind r
bind r source-file ~/.tmux.conf

# Bind prefix + c to create a new window at the current window's path/location
unbind c
bind c new-window -c "#{pane_current_path}"

# Set Ctrl + s as prefix
set -g prefix C-s

# Enable mouse
setw -g mouse on

# Start window index numbering from 1
set -g base-index 1

# Start pane index numbering from 1
set -g pane-base-index 1

# Initialize TPM
run -b '~/.tmux/plugins/tpm/tpm'
